### ISSUE TITLE
[Feature Request] Shared tooltip/crosshair

### ISSUE THREAD

**Issue by royemmerich** [NatelEnergy/grafana-discrete-panel#10]
It would be great if the discrete panel could support the shared tooltip/crosshair functionality.

![screen shot 2017-04-02 at 15 42 19](https://cloud.githubusercontent.com/assets/3904395/24587713/bbce25a8-17bb-11e7-8af8-e9aebc14428e.png)

**Comment by ryantxu** [comment]
will be released in 0.0.3

**Comment by royemmerich** [comment]
Unfortunately it looks like tooltips don't work in v0.03 when you select shared tooltip (as opposed to the shared crosshair option). They do still appear when hovering over the legend though.

**Comment by royemmerich** [comment]
It also seems there is cross hair shifting going on, depending on where you place your mouse cursor.

In the first image you will notice the following:

- My mouse is hovering over the upper graph, indicated by the tooltip (cursor not captured in screenshot)
- The discrete panel cursor is graphically indicating that it is over the blue state (defined as balancing)
- However it claims, via the textual indicator, that it is still in the no balancing state.
- This is not the expected behaviour.

<img width="1189" alt="screen shot 2017-04-19 at 11 10 08" src="https://cloud.githubusercontent.com/assets/3904395/25172450/5b9fe994-24f1-11e7-96af-a8d6fef08692.png">

If I then attempt the same exercise, this time hovering my mouse cursor over almost the same position on the discrete panel I end up seeing the following:

- Both the discrete panel cursor and textual indicator seem to agree that I'm in the balancing state
- This is the expected behaviour.

<img width="1172" alt="screen shot 2017-04-19 at 11 11 36" src="https://cloud.githubusercontent.com/assets/3904395/25172682/1693bf8c-24f2-11e7-8ee3-0d12493758da.png">

P.S. I placed the dashboard in shared crosshair mode which is why the discrete panel tooltip is visible in the second image.

**Comment by ryantxu** [comment]
nevermind... i found some issues and a new approach

**Comment by ryantxu** [comment]
this should be fixed in master and released with 0.0.4 -- holler if you have issues

**Comment by royemmerich** [comment]
It seems the tooltip position isn't quite right. It is located very far from the data source, as shown in the image below:

<img width="447" alt="screen shot 2017-04-21 at 20 45 40" src="https://cloud.githubusercontent.com/assets/3904395/25291994/91ac64a6-26d4-11e7-9ad9-f3253a4d0c2d.png">

**Comment by royemmerich** [comment]
With a discrete panel which has two metrics, and the "Highlight on hover" option selected, no tooltip is shown, except when hovering over the legend.

<img width="427" alt="screen shot 2017-04-21 at 20 55 38" src="https://cloud.githubusercontent.com/assets/3904395/25292080/f6bfac7c-26d4-11e7-928b-3d5565b971c5.png">
