### ISSUE TITLE
Cannot See Actual Metric Names

### ISSUE THREAD

**Issue by JizZuS** [NatelEnergy/grafana-discrete-panel#115]
Since my Grafana 7.0 update, I cannot see the metric names, even when the option is enabled in panel settings. Instead of the metric name, the "Value" text is shown. I've tried using the updated version of this plugin but without success.

Thank you for any tips on how to resolve this issue.

## Expected Behavior
Show alias as the metric name.

## Current Behavior
Showing "Value" as metric name.

This is current behaviour:
![image](https://user-images.githubusercontent.com/7282431/83722190-d7621780-a63c-11ea-8c85-3fb3205e0522.png)
This is behaviour before Grafana update:
![image](https://user-images.githubusercontent.com/7282431/83722370-23ad5780-a63d-11ea-8bed-c224833eef42.png)

**Comment by fuslwusl** [comment]
Have the same problem! So the plugin is useless without this information.

**Comment by bdattilo** [comment]
Same issue here.

**Comment by raydog153** [comment]
Same issue, what version of plugin got installed? I am noticing that I have 0.0.10-dev installed which was default. Where is v0.1.0 per changelog?

**Comment by bdattilo** [comment]
Grafana 7.0.3, Discrete Panel 0.0.10-dev as well.

**Comment by picnicorama** [comment]
Same issue here ...
Grafana 7.0.5, Discrete Panel 0.0.10-dev

**Comment by Rushmed** [comment]
For me the same issue but only @0.0.10-dev, 0.0.9 is working for me on Grafana 7.0.5.

**Comment by JizZuS** [comment]
> For me the same issue but only @0.0.10-dev, 0.0.9 is working for me on Grafana 7.0.5.

You're right! Thanks for the tip, it really works!

**Comment by raydog153** [comment]
So to sound so naive, but how do you downgrade or install a specific version?

**Comment by agross** [comment]
@raydog153 https://github.com/agross/ansible-raspi/commit/bc8e4a25be7f83969064aa7a1a06dfab3fb6af30
