### ISSUE TITLE
'Alias by' doesn't show when 'write metric names' i checked with grafana 7 (it works in grafana 6)

### ISSUE THREAD

**Issue by omarcin31** [NatelEnergy/grafana-discrete-panel#120]

**Comment by joakimkejser** [comment]
Hi,

I'm having the same issue. However, alias by does not seem to make a difference - it just shows "value" when write `metric names is checked`.

![image](https://user-images.githubusercontent.com/2860792/87256513-a2df4800-c493-11ea-8ffb-a951b706788c.png)

Thanks for a great plugin. Does exactly what I need.

Br,
Joakim

**Comment by omarcin31** [comment]
I got it working by installing version 0.0.9 with grafana 7 instead version 1.0.0-dev
Hopefully this will be fix in a next version.
and i agree Joakim - great plugin!

**Comment by ryantxu** [comment]
I just pushed v0.1.0 -- can you try with that?  If it is still an issue please reopen

**Comment by kovaga** [comment]
Just updated to ver 0.1.0, the issue still persists.
