### ISSUE TITLE
[Enhancement] Prevent metric name and first value overlap

### ISSUE THREAD

**Issue by royemmerich** [NatelEnergy/grafana-discrete-panel#13]
With the "Write Metric Names" option selected one ends up with the first value in the discrete series overlapping the metric name, as shown in the image below

<img width="546" alt="screen shot 2017-04-20 at 11 24 26" src="https://cloud.githubusercontent.com/assets/3904395/25223771/a4fc5020-25bc-11e7-8bf2-ef5255251f89.png">

However when one hovers the mouse over the metric name it then disappears, clearly showing what the first value is (see image below):

<img width="548" alt="screen shot 2017-04-20 at 11 25 05" src="https://cloud.githubusercontent.com/assets/3904395/25224028/771770d0-25bd-11e7-94e4-7834af2a23c1.png">

It would be super if, when the first value is to be shown, it would always cause the metric name to fade away, thereby making it clearly visible.

**Comment by ryantxu** [comment]
at 0.0.5, i hide the metric name on hover...
