### ISSUE TITLE
[Enhancement Request] Option to display count of transitions.

### ISSUE THREAD

**Issue by codersaur** [NatelEnergy/grafana-discrete-panel#14]
Thanks for this panel, it's something Grafana has been sorely lacking for a very long time! :)

As title says, I would like to be able to display a count of transitions.

Even better would be some kind of histogram of transition count (e.g. number of transitions per hour, with hourly buckets).

**Comment by ryantxu** [comment]
in v0.0.5, it can show the transition count in the legend.

This histogram suggestion... i don't fully understand - why not just use the new histogram panel?
