### ISSUE TITLE
Legend and percentages

### ISSUE THREAD

**Issue by 4hopp** [NatelEnergy/grafana-discrete-panel#16]
Hi,
Nice panel; sadly, I experienced some problems with the legend.

Sometimes not all occuring values are represented in the legend area:
![screenshot1](https://cloud.githubusercontent.com/assets/17498179/26301698/3e6e161a-3ee2-11e7-8e9a-c02320dab8a0.png)

Also, percentage sometimes exceeds 100%:
![screenshot2](https://cloud.githubusercontent.com/assets/17498179/26301699/3e7a5678-3ee2-11e7-8b87-e40856219324.png)

Thanks for your work!

**Comment by ryantxu** [comment]
should be fixed in v0.0.5 (next release)
