### ISSUE TITLE
What data sources does this panel support?

### ISSUE THREAD

**Issue by dbeckham** [NatelEnergy/grafana-discrete-panel#17]
It's not really clear which different Grafana datasources that this plugin will work with.  Any datasource that would return a value shows the error `_.isNil is not a function`. 

I'm assuming I can use value and range mappings to convert values to text, or be able to use a metrics that only contains 0 or 1 values such as an AWS CloudWastch HealthStatus cluster metric, but they all end up showing this error: https://dl.dropboxusercontent.com/s/kx4bik0mmc6ir5g/2017-06-13%20at%201.05%20PM.png

What data sources does this panel actually support?

**Comment by ryantxu** [comment]
I have only ever tried this with InfluxDB and the internal 'test' data source, but there should be no reason it would not work with others.

_.isNil is a lodash function, what version of grafana are you using?

**Comment by dbeckham** [comment]
I'm using version 3.1.1 run from the [Grafana Docker images](https://hub.docker.com/r/grafana/grafana/), tag: `3.1.1-1470047149`.

After doing some looking around, I realized that InfluxDB might definitely be what you were targeting during testing. I have several data sources, Graphite, Cloudwatch and Elasticsearch that I use for metrics, so I would be willing to help troubleshoot.

One specific use case for me would be AWS Redshift cluster uptime. A metric is available from Cloudwatch, named [HealthStatus](http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/rs-metricscollected.html) that is either a 1 or 0, indicating Healthy (1) or Unhealthy (0), and seems like a good candidate for a simple Discrete graph.  I currently use this data for a [SingleStat](http://docs.grafana.org/features/panels/singlestat/) panel.

Is there anything I can get from my installation, or data sources that would help track down the problem?

**Comment by ryantxu** [comment]
can you check the chrome console window when you get the _isNil error?  it should say some more info about where the error happens.

without looking (i'm out of the office this week), I'm guessing the results may be returned in table format, not the series format... i have not tried to table format yet, but should be easy to support.

**Comment by dbeckham** [comment]
Ok, hopefully this is in a format readable enough. While on the new panel page (`/dashboard/new?panelId=1&fullscreen&edit&editorTab=Metrics`) with a CloudWatch data source query defined,  I cleared my console in Chrome, and then  clicked the refresh button at the top right of the grafana interface. Here is the output from the Chrome console:

```
canvas-metric.js:38 onRefresh()
canvas-metric.js:38 onRefresh()
boot.1649cbaa.js:36 TypeError: _.isNil is not a function
    at DiscretePanelCtrl.formatValue (module.js:275)
    at eval (module.js:373)
    at Function.Ya (boot.1649cbaa.js:41)
    at eval (module.js:371)
    at Function.Ya (boot.1649cbaa.js:41)
    at DiscretePanelCtrl.onDataReceived (module.js:361)
    at e.emit (boot.1649cbaa.js:39)
    at a.emit (boot.1649cbaa.js:39)
    at DiscretePanelCtrl.f.handleQueryResult (boot.1649cbaa.js:41)
    at h (boot.1649cbaa.js:36)
(anonymous) @ boot.1649cbaa.js:36
(anonymous) @ boot.1649cbaa.js:35
h @ boot.1649cbaa.js:36
(anonymous) @ boot.1649cbaa.js:36
$eval @ boot.1649cbaa.js:36
$digest @ boot.1649cbaa.js:36
$apply @ boot.1649cbaa.js:36
(anonymous) @ boot.1649cbaa.js:36
e @ boot.1649cbaa.js:35
(anonymous) @ boot.1649cbaa.js:35
module.js:60 onDataError TypeError: _.isNil is not a function
    at DiscretePanelCtrl.formatValue (module.js:275)
    at eval (module.js:373)
    at Function.Ya (boot.1649cbaa.js:41)
    at eval (module.js:371)
    at Function.Ya (boot.1649cbaa.js:41)
    at DiscretePanelCtrl.onDataReceived (module.js:361)
    at e.emit (boot.1649cbaa.js:39)
    at a.emit (boot.1649cbaa.js:39)
    at DiscretePanelCtrl.f.handleQueryResult (boot.1649cbaa.js:41)
    at h (boot.1649cbaa.js:36)
boot.1649cbaa.js:41 Panel data error: TypeError: _.isNil is not a function
    at DiscretePanelCtrl.formatValue (module.js:275)
    at eval (module.js:373)
    at Function.Ya (boot.1649cbaa.js:41)
    at eval (module.js:371)
    at Function.Ya (boot.1649cbaa.js:41)
    at DiscretePanelCtrl.onDataReceived (module.js:361)
    at e.emit (boot.1649cbaa.js:39)
    at a.emit (boot.1649cbaa.js:39)
    at DiscretePanelCtrl.f.handleQueryResult (boot.1649cbaa.js:41)
    at h (boot.1649cbaa.js:36)
```

**Comment by ryantxu** [comment]
Weird _.isNil is a lodash function that has been around since 4.0.0
https://lodash.com/docs/4.17.4#isNil

Are you seeing lodash loaded in your network extension?  I see:
/public/vendor/lodash/dist/lodash.js?bust=1497478527961

and it loads version '4.15.0'

any other errors in the chrome developer console?

**Comment by dbeckham** [comment]
I do not see a request for that URL in the network extension output, but I do see `lodash.js` referenced in the response from the requests for `boot.*.js`.  

I did a little digging, though, and I think what is going on is that Grafana 3.x (3.1.1 latest) was using [lodash.js version 2.4.1](https://github.com/grafana/grafana/blob/v3.1.1/public/vendor/lodash.js), which doesn't have the `isNil()` method. Grafana 4.0 switched to [lodash.js version 4.15.0](https://github.com/grafana/grafana/blob/v4.0.0-beta1/public/vendor/lodash/lodash.js), which does include the `isNil()` method as you said.

I think the problem is that the Discrete panel just doesn't support Grafana 3.x, but the [Grafana.com Plugin Page](https://grafana.com/plugins/natel-discrete-panel) shows `3.x.x` support.

**Comment by ryantxu** [comment]
I'll close this issue now, but see #18 for your solution.  Likely pretty easy
