### ISSUE TITLE
Time shown on X-axis

### ISSUE THREAD

**Issue by dstreppa** [NatelEnergy/grafana-discrete-panel#2]
Thank you very much for this panel, it is very useful. 

I would like to request you if it is possible to show the time directly on the X-axis as for the typical Grafana graphs.

And again, great job!

**Comment by scjoiner** [comment]
+1 for us!

**Comment by TambetP** [comment]
+1

**Comment by nbrownus** [comment]
!!

**Comment by ryantxu** [comment]
Looks like @AlexanderWert has made progress on this...  https://github.com/NovaTecConsulting/novatec-grafana-discrete-panel/issues/1

**Comment by ryantxu** [comment]
This is now in master and will be released with v0.0.7 

https://github.com/grafana/grafana-plugin-repository/pull/245

Lets make new issues for improvements.
