### ISSUE TITLE
Incorrect state being indicated

### ISSUE THREAD

**Issue by royemmerich** [NatelEnergy/grafana-discrete-panel#21]
I have a line graph showing the voltage of a particular lithium battery consisting of 16 separate cells (3 V each, in series, to form a 48 V battery). The image below shows the information correctly depicted. A line graph above showing the cell voltage minima and maxima, the difference between the two and a discrete panel (v0.5) showing the cell balancing activity (depicted by either a 0 or 1 in the InfluxDB database).

![screen shot 2017-07-31 at 23 34 19](https://user-images.githubusercontent.com/3904395/28799432-da6dc1ee-7648-11e7-9cd4-6efafdcef0ac.png)

Sometimes, however the discrete panel doesn't function correctly. As you can see in the image below there is no data for the time period shown (i.e. the blank line graph), however the discrete panel tells me balancing is occurring 100% of the time.

![screen shot 2017-07-31 at 19 13 01](https://user-images.githubusercontent.com/3904395/28799274-3b7e05ee-7648-11e7-9aa6-36bf309231b2.png)

This issue also comes up in other circumstances. Take a look at the image below and notice the balancing state at this particular cursor position (i.e. no balancing):

![screen shot 2017-07-31 at 23 45 09](https://user-images.githubusercontent.com/3904395/28800007-1c14a926-764b-11e7-889d-3df9e9c6f322.png)

Now if I take the exact same graphs and just zoom in a little bit, notice what the balancing state is at the exact same timestamp as the image above (i.e. balancing):

![screen shot 2017-07-31 at 23 46 05](https://user-images.githubusercontent.com/3904395/28799910-bced3850-764a-11e7-9443-27522c6258c5.png)

I'm really not sure what is going on here but it is fairly critical to the usefulness of this panel. Just for reference purposes, here is the InfluxDB query I'm using:

```
SELECT distinct("balancing_state") FROM "bms_balancer_status" WHERE "bms_balancer_id" =~ /^$bms_balancer_1$/ AND $timeFilter GROUP BY time($interval) fill(none)
```

Just let me know if I can be of any further help to sort this issue out.

**Comment by ryantxu** [comment]
There are two issues here

1. This panel assumes the last value it got continues.  This does funny things if you are looking at the edges of real data.  We should add an issue to make this optional.  This is what I think you are seeing in your first example.  

2. I am not sure i understand using 'distinct' in this query *and* a GROUP BY.  Have you tried just using distinct without the GROUP BY?  If you are worried about too many results you could do a GROUP BY and use 'mode("balancing_state") -- but this will obviously have lower precision

**Comment by ryantxu** [comment]
> As you can see in the image below there is no data for the time period shown (i.e. the blank line graph), however the discrete panel tells me balancing is occurring 100% of the time.

Have you checked the chrome developer console to see what queries are actually getting sent to influx?  If it is showing 'balancing' that is coming from the query somehow

**Comment by ryantxu** [comment]
also, maybe try fill(previous) rather than fill(none)

**Comment by royemmerich** [comment]
Upon your recommendations I now have the following query and it seems to be producing a more acceptable result:

```
SELECT "balancing_state" FROM "bms_balancer_status" WHERE "bms_balancer_id" =~ /^$bms_balancer_1$/ AND $timeFilter fill(previous)
```

This matches [the suggested query for annotations with InfluxDB](http://docs.grafana.org/features/datasources/influxdb/#annotations).

The reason for the `distinct()` part in my original query was, I thought, to ensure no averaging takes place. If you take a look at the following image you will notice the seemingly continuous balancing block on the right hand half of the discrete panel:

<img width="1655" alt="screen shot 2017-08-01 at 10 42 04" src="https://user-images.githubusercontent.com/3904395/28816905-cea6737a-76a6-11e7-9481-b300e6bebd7f.png">

However if I zoom in and place my cursor on the same spot, it shows it as being in a no balancing state:

<img width="1657" alt="screen shot 2017-08-01 at 10 40 50" src="https://user-images.githubusercontent.com/3904395/28816956-f9266dc6-76a6-11e7-950e-85efde68de9e.png">

Despite my previous thoughts about using `distinct()`, it is not practical to show each and every balancing/no balancing state when there is such a high density of state changes.

**Comment by ryantxu** [comment]
Can you do distinct without a group by and add a LIMIT 10000 (or something like that)?

Then you would have everything until you zoom out far.  I'm not really sure the best solution when you have LOTS of transitions.

I'll close this issue and let you open a new one about showing the last value beyond the the last value returned from the query
