### ISSUE TITLE
hover makes metric name disappear

### ISSUE THREAD

**Issue by blysik** [NatelEnergy/grafana-discrete-panel#26]
Hi, when I hover over a row to see some details, the metric name at the left side of the row disappears while hovering. Is there any way to prevent that from happening?  I have enough rows that it's confusing if those labels go away.

Thanks!

**Comment by TambetP** [comment]
I have not found a way to turn it off, but it would be a very useful to have the option to turn it on or off.

**Comment by fisheyeThuds** [comment]
An other option could be to only make disappear the hovered row.

**Comment by gperez** [comment]
this seems to have been introduced recently.

I am using the plugin version 0.04 with Grafana v4.5.2, and the metric names do not disappear while hovering.

However, upgrading either the plugin or grafana to a newer version trigger the issue...

**Comment by ryantxu** [comment]
should be improved in 0.7.  Post a new issue if there are changes you want to see.  Now it hides only when the text will collide
