### ISSUE TITLE
Colors from Grafana's palette

### ISSUE THREAD

**Issue by jonyrock** [NatelEnergy/grafana-discrete-panel#29]
We can use colours palette same as colours in Graph Panel 

It would look like this: 
<img width="764" alt="screen shot 2017-11-02 at 17 16 28" src="https://user-images.githubusercontent.com/1022757/32340137-9c5ebb18-bff1-11e7-8c74-72d289ef724b.png">

**Comment by ryantxu** [comment]
+1

**Comment by jonyrock** [comment]
https://github.com/CorpGlory/grafana-discrete-panel/commit/a98b7f821a4a8a9b4b9a8c6e9e81ce64f4923616

**Comment by ryantxu** [comment]
looks good, can you make a pull request or just merge?

**Comment by jonyrock** [comment]
@ryantxu working on this

**Comment by jonyrock** [comment]
@ryantxu I made pull request, we haven't defined workflow yet. Are you going to review it first?

**Comment by ryantxu** [comment]
closed with #30
