### ISSUE TITLE
[Feature Request] support local snapshots

### ISSUE THREAD

**Issue by ankon** [NatelEnergy/grafana-discrete-panel#35]
I've tried to share a local snapshot of a dashboard with the discrete panel used. When checking the snapshot however it seems all data for the discrete panel is lost, and nothing is shown.

**Comment by ryantxu** [comment]
i'll take a look... have not tried to use snapshots before

**Comment by ryantxu** [comment]
This was added in #48 thanks @londonanthonyoleary

It is now in master and will be in the next release (not yet scheduled).
