### ISSUE TITLE
Bug in Grafana 4.6.2

### ISSUE THREAD

**Issue by needlerp** [NatelEnergy/grafana-discrete-panel#36]
I've just updated to Grafana 4.6.2, and now all my Discrete panels won't show, and give the following error:
undefined is not an object (evaluating 't.rangeRaw.from')

**Comment by xoseperez** [comment]
I've also hit this issue. Removing the this.panel.targets check at the begining of the issueQueries method solves the issue but I don't know if it's needed for some other reason:

`
if (!this.panel.targets || this.panel.targets.length === 0) {
   return this.$q.when([]);
}
`

**Comment by ryantxu** [comment]
I just pushed a change that avoids calling `issueQueries `

Can you check if: 037e2abef5ea2cd964c75d3583b81bbafc8975be  fixes this issue?

**Comment by sbe08** [comment]
I am also experiencing the same error with grafana 5.1.3 and discrete-panel 0.0.8-pre.  The stack trace is as follow: 

`getTimeFilter@http://10.0.1.205:3000/public/build/0.5c89ac3fc7a3e78b3629.js:7:141402
query@http://10.0.1.205:3000/public/build/0.5c89ac3fc7a3e78b3629.js:7:137714
issueQueries@[native code]
u@http://10.0.1.205:3000/public/build/vendor.97f08ee4f8b84dae9405.js:87:69120
http://10.0.1.205:3000/public/build/vendor.97f08ee4f8b84dae9405.js:87:69566
$digest@http://10.0.1.205:3000/public/build/vendor.97f08ee4f8b84dae9405.js:87:75263
$apply@http://10.0.1.205:3000/public/build/vendor.97f08ee4f8b84dae9405.js:87:77083
http://10.0.1.205:3000/public/build/vendor.97f08ee4f8b84dae9405.js:87:73141
i@http://10.0.1.205:3000/public/build/vendor.97f08ee4f8b84dae9405.js:87:21983
http://10.0.1.205:3000/public/build/vendor.97f08ee4f8b84dae9405.js:87:23441`

**Comment by sbe08** [comment]
I am also experiencing the same error message with grafana 5.1.3 and discrete-panel 0.0.8-pre. The stack trace is:
`getTimeFilter@http://10.0.1.205:3000/public/build/0.5c89ac3fc7a3e78b3629.js:7:141402
query@http://10.0.1.205:3000/public/build/0.5c89ac3fc7a3e78b3629.js:7:137714
issueQueries@[native code]
u@http://10.0.1.205:3000/public/build/vendor.97f08ee4f8b84dae9405.js:87:69120
http://10.0.1.205:3000/public/build/vendor.97f08ee4f8b84dae9405.js:87:69566
$digest@http://10.0.1.205:3000/public/build/vendor.97f08ee4f8b84dae9405.js:87:75263
$apply@http://10.0.1.205:3000/public/build/vendor.97f08ee4f8b84dae9405.js:87:77083
http://10.0.1.205:3000/public/build/vendor.97f08ee4f8b84dae9405.js:87:73141
i@http://10.0.1.205:3000/public/build/vendor.97f08ee4f8b84dae9405.js:87:21983
http://10.0.1.205:3000/public/build/vendor.97f08ee4f8b84dae9405.js:87:23441`

**Comment by sbe08** [comment]
Thanks! Let me know if I can provide any trace or configuration info to help you...

Sylvain

**Comment by ryantxu** [comment]
@sbe08 -- I edited the comment... so maybe you did not see it :)  I can't reproduce, what query? and does the same query work in the standard graph panel?

**Comment by sbe08** [comment]
I feel dumb this morning… I log in my system and everything works fine! I had upgraded Grafana and Discrete yesterday as I was having the aforementioned issue. It seems it needed time to flush out the error. 

Thanks for your quick involvement and sorry to have bothered you.
