### ISSUE TITLE
Scrollbar missing on embedded panel with Grafana v5

### ISSUE THREAD

**Issue by Ryuzavi** [NatelEnergy/grafana-discrete-panel#45]
Hey.  Not sure if this will be fixed with the recent commits but after the upgrade to Grafana v5.0.0 the panel lost it's scrollbar when it's embedded in an iframe.  

This means if the panel is bigger than the iframe area it just gets cut off.

**Comment by ryantxu** [comment]
I just added: `static scrollable = true;` This is new in v5.  Let me know if it helps

**Comment by Ryuzavi** [comment]
Ah awesome.  Is this released anywhere?

**Comment by ryantxu** [comment]
should be released soon...  grafana guys check things before publishing

https://github.com/grafana/grafana-plugin-repository/pull/245
