### ISSUE TITLE
404 Error when upgrading to 0.0.7

### ISSUE THREAD

**Issue by Diegonarducci88** [NatelEnergy/grafana-discrete-panel#46]
Error: 
Plugin Error
HTTP Error (404) Not Found

**Comment by ryantxu** [comment]
More information please?  Where are you looking?  

What do you seen in the chrome debug tools?

**Comment by ncmilhouse** [comment]
I had the same error after upgrade.  Opening a dashboard with a discrete panel gave a 404 error, and everything displayed EXCEPT the discrete panels.

I copied the .html files from data\plugins\natel-discrete-panel\dist\partials to data\plugins\natel-discrete-panel\dist and restarted Grafana.  That seemed to fix it.

**Comment by ncmilhouse** [comment]
Oh, the message in the logs was
2018-03-29T07:55:34-0400 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=milhouse method=GET path=/public/plugins/natel-discrete-panel/module.html status=404 remote_addr=4.34.16.158 time_ms=15 size=23334 referer="http://xxx.xxx.xxx.xxx:3000/d/000000002/smartthings-power-usage?refresh=5m&orgId=1"

**Comment by ryantxu** [comment]
Weird.  I wonder if it is a caching issue?

Yes, the html file moved from:
`/public/plugins/natel-discrete-panel/module.html`
to
`/public/plugins/natel-discrete-panel/partials/module.html`

But the reference to it also did:
https://github.com/NatelEnergy/grafana-discrete-panel/blob/master/dist/module.js#L841


@ncmilhouse -- if you shift+F5 (clear cache) and delete your copied files, does it still get an error?

**Comment by ncmilhouse** [comment]
I deleted the 5 .html files from dist, leaving them in partials as original.  Re-started Grafana.  Re-opened my Grafana dashboard and it still worked correctly.  Shift-F5 to clear cache.  Still worked correctly.

I believe you are correct in that it's just a caching issue.  Fix for anyone else hitting this error is simply Shift+F5.

**Comment by ryantxu** [comment]
I'll close this since the only real solution is in grafana.  https://github.com/grafana/grafana/issues/11446
