### ISSUE TITLE
Prometheus issue with "step" value in query

### ISSUE THREAD

**Issue by jreineke-nli** [NatelEnergy/grafana-discrete-panel#49]
Hi,

I am currently facing some issues with my prometheus query inside the discrete panel. I have added my queries to the discrete panel and set the time range to "previous month".
With this big time range I am trying to calculate the server uptime in % and how long a server wasn't available. Because of this i have to set the "min step" option in Grafana to "60s". But somehow grafana won't add this value to the prometheus query. Inside the query the "step=" Option stays the same no matter what option I am choosing for "min step".

Furthermore I noticed that this "step=" option is diffrent from the Browser I am using.
I have tested it with Firefox and Chrome. In Firefox the step value inside the query is "900" and for Chrome it is "1200".

I don't know if this is actually a problem from the plugin or Grafana itself. Currently i couldn't verify this behaviour with the bultin Graph Panel from Grafana.

**Comment by ryantxu** [comment]
this sounds like a question better asked on the grafana list.  I don't use prometheus so I can't help much.  

Do you know if there is a `min step` configured in the datasource?  InfluxDB has something similar.

The 900 vs 1200... i'm guessing your browser windows were are different width.  The query gets built based on the size of the element it needs to fill.  (wider windows ask for more points)
