### ISSUE TITLE
show in legend  text from value mappings

### ISSUE THREAD

**Issue by tvm2018** [NatelEnergy/grafana-discrete-panel#50]
How show in legend  text from value mappings?
I set up a value mapping, but not the text but the value is displayed in the legend. How to fix?
![1](https://user-images.githubusercontent.com/38098392/38355776-92433ae8-38c6-11e8-973c-8f138e10e605.PNG)
![2](https://user-images.githubusercontent.com/38098392/38355843-b9cabcda-38c6-11e8-8af2-b0277d1bd564.png)
Only one value displays text-this is null
Thanks

**Comment by tvm2018** [comment]
it was necessary to select in Numeric Conversion-none

**Comment by tvm2018** [comment]
![1](https://user-images.githubusercontent.com/38098392/39232352-b552a708-4875-11e8-9f05-7a54685a46f5.PNG)
on the "Mappings" tab

**Comment by zhoumin8023** [comment]
However, this method still has problems. For example, before choosing Conversion-none, the display looks like this:
![image](https://user-images.githubusercontent.com/34366341/39235259-02647562-48a8-11e8-8134-1aa48cf550a3.png)
 But after the conversion-none is selected, it is displayed as follows，
![image](https://user-images.githubusercontent.com/34366341/39235384-56b269e4-48a8-11e8-956b-ad00d10ad052.png)

**Comment by do11** [comment]
> it was necessary to select in Numeric Conversion-none

Thanks! This is very helpful and unintuitive in the same time.
