### ISSUE TITLE
Direct link rendered image failed

### ISSUE THREAD

**Issue by jreineke-nli** [NatelEnergy/grafana-discrete-panel#51]
I'm trying to render the discrete panel as an image via the "Direct link rendered image" Button inside the share panel option.

The Website which will open then just loads and after about 1 minute I'm getting an error page.

Inside the Grafana Logs I found this:

```
lvl=info msg=Rendering logger=png-renderer path="d-solo/XGWXldimz/reporting?orgId=1&panelId=6&from=1519858800000&to=1522533599999&width=1000&height=500&tz=UTC%2B02%3A00"
lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/render/d-solo/XGWXldimz/reporting status=500 remote_addr=192.168.1.141 time_ms=60003 size=1763 referer="http://grafana:3000/d/XGWXldimz/reporting?orgId=1"
lvl=eror msg="failed to render an image" logger=png-renderer error="signal: killed"
```

I have also tried to set the log level from grafana to debug, but nothing more is displayed here.

On the error site I am getting I see the following message: `Timeout error. You can set timeout in seconds with &timeout url parameter"`.  Unfortunately setting the timeout parameter to a very high number doesnt help aswell here.

**Comment by Tobias007** [comment]
I have the same issue. All other panels work to render. It must be something specific with the discrete panel.

**Comment by ryantxu** [comment]
I see the same issue and will look into it

**Comment by ryantxu** [comment]
fixed in master, this will be included in the 0.0.8 release

**Comment by matthenning** [comment]
@jreineke-nli With today's release of 0.0.8 I have successfully tested this feature by using the version from the official Grafana repository.

**Comment by jreineke-nli** [comment]
I can confirm this aswell. After the new release the rendering is working.
Thanks for the fix.
