### ISSUE TITLE
Grafana 5.1 breaks legend

### ISSUE THREAD

**Issue by mlamoure** [NatelEnergy/grafana-discrete-panel#54]
I believe the 5.1 update breaks the legend for the Discrete Panel.  Here is a screenshot of what is happening:

<img width="1255" alt="screen shot 2018-05-02 at 4 50 02 pm" src="https://user-images.githubusercontent.com/1021890/39548527-e1888320-4e28-11e8-883a-1cfa3dbc8483.png">

**Comment by ryantxu** [comment]
yup, 5.1 broke things.  Fixed in master and will release soon
