### ISSUE TITLE
Horizontal scrollbar?

### ISSUE THREAD

**Issue by ScriptByScript** [NatelEnergy/grafana-discrete-panel#55]
Why is there a navbar on the bottom of all of our discrete panels? I keep our Grafana very updated, so perhaps a recent update broke this (or added it)? It looks terrible. 
![navbar](https://user-images.githubusercontent.com/28926218/39577570-52b83c74-4ea7-11e8-89f6-602a9f759266.png)

**Comment by ryantxu** [comment]
I am unable to reproduce this... can you post the 'Panel JSON'?  What version of grafana and the plugin?

I'm guessing this is an issue with 5.1 and the changes to how scrollbars work.

**Comment by ScriptByScript** [comment]
[HorizontalBar.zip](https://github.com/NatelEnergy/grafana-discrete-panel/files/1971916/HorizontalBar.zip)

 Grafana v5.1.0 (commit: 844bdc53a)

**Comment by ryantxu** [comment]
I think this will be fixed in the 0.0.8 (master) release.  Are you able to easily test that?

**Comment by ScriptByScript** [comment]
What's the best way to install it other than the quick one-liner from Grafana (usually how I install). Yes, I'm a n00b.

**Comment by 2-5** [comment]
I have the same problem in Grafana 5.1.3 and plugin version 0.0.7.

Could you please push the 0.0.8 version out?

**Comment by ryantxu** [comment]
> Could you please push the 0.0.8 version out?

I wish I had control :(

https://github.com/grafana/grafana-plugin-repository/pull/273

**Comment by ScriptByScript** [comment]
Looks like it's now fixed, thanks for the prompt resolution!
