### ISSUE TITLE
Tooltip consistent with graph panel

### ISSUE THREAD

**Issue by bencaldwell** [NatelEnergy/grafana-discrete-panel#61]
When I use the discrete panel under a graph panel with shared tooltip I see an inconsistent presentation that makes it harder to interpret the information from the discrete panel.

I would like to suggest an enhancement where the tooltip information is presented in a tabular form similar to the graph panel with all active metrics shown e.g. several rows of the format:

**| pen colour | metric | value | start time | end time | duration |**

**Comment by co-al-re** [comment]
I second this. One of my gripes about the usability is on hover. The metric tags at left on panel are replaced by values and then the tooltip doesn't display the metric I'm hovering over. Its hard on wide graphs to correspond both together.

**Comment by mghomedev** [comment]
At least mention the metric name in the hoover tooltip, otherwise the whole discrete panel makes no sense when analyzing many series at once (you never know at which row you are looking exactly)
