### ISSUE TITLE
Don't hide series names

### ISSUE THREAD

**Issue by co-al-re** [NatelEnergy/grafana-discrete-panel#62]
When the mouse hovers over the panel the series names disappear. That combined with the uninformative tooltip makes it impossible to correlate both the hovered value with the series.

Hovered:
![6-22-2018 4-13-58 pm](https://user-images.githubusercontent.com/40505859/41802707-ad55162c-7637-11e8-8b2d-4ebcb93d9208.png)

Unhovered:
![6-22-2018 4-13-49 pm](https://user-images.githubusercontent.com/40505859/41802708-ad707d04-7637-11e8-87ba-9da9db2c354b.png)

**Comment by MartinRoenneburg** [comment]
+1

**Comment by redge76** [comment]
I'm using this panel to monitor the status of websites. Each url is a serie.
When the mouse hovers over the panel the series names disappear and I can't tell which system is up or donwn ...

**Comment by redge76** [comment]
perfect. thx
