### ISSUE TITLE
Documentation on how to install the latest master version from git repo

### ISSUE THREAD

**Issue by kccheung** [NatelEnergy/grafana-discrete-panel#67]
Can anyone help provide a guide on how to install master branch of this plugin on my grafana from scratch?

Is it just by putting the whole directory `grafana-discrete-panel` to `/var/lib/grafana/plugins` after doing `yarn install` and `yarn build`?

**Comment by ryantxu** [comment]
yes...  and then restarting grafana (unless it was already loaded)

Was it not working or something?

**Comment by kccheung** [comment]
Yes, it is working, thank you.
