### ISSUE TITLE
Tooltip with more accurate duration information

### ISSUE THREAD

**Issue by dennisdahlmann** [NatelEnergy/grafana-discrete-panel#75]
Hi,
first of all thank you for the discrete panel, we are using it to monitor the state of a machine.

Is it possible to show a more accurate duration in the tooltip of the panel?
Your screenshot shows the problem:
![screenshot-single-2](https://user-images.githubusercontent.com/44778507/48006452-c0cca500-e115-11e8-80a6-08d0673e2937.png)
The duration is mentioned as "a day", but the 30 minutes are ignored. 

Or see this example:
![example2](https://user-images.githubusercontent.com/44778507/48006928-cb3b6e80-e116-11e8-8c4a-755fb98543c1.png)
Instead of "4 hours", "3 hours 30 minutes" would be better.

Do you think it is possible to add more accuracy to the duration information in the tooltip?
Maybe it is possible to configure the duration time units, e.g. "hour;minute;second" and all duration will be shown in this units, even if it is a higher unit (day) available. So for your screenshot example of "a day" it would be "24 hours 30 minutes".

BR

**Comment by ryantxu** [comment]
sounds good -- open to contributions

**Comment by NerdyProjects** [comment]
I have the same problem :-) I use discrete-panel to show running times for a heating system and the user should calculate the gas usage by reading the time of a certain state.

The duration is given by `momentjs::humanize`. There is an upstream feature request open as well - https://github.com/moment/moment/issues/348.
One of the last comments posts a snippet that looks useful here. But I also feel a bit lazy to put this into place now...

**Comment by clink-aaron** [comment]
The fix for this is done, and looks like it will go out with v0.0.9.

 When does that release go live?
