### ISSUE TITLE
[Feature Request] Make font size settable

### ISSUE THREAD

**Issue by royemmerich** [NatelEnergy/grafana-discrete-panel#8]
It would be great if you could set the font size of the values shown in each line. For example if I reduce the row height to show a lot of discrete rows, I'd also like to reduce the font size to match the discrete row height.
 
![screen shot 2017-04-02 at 15 29 11](https://cloud.githubusercontent.com/assets/3904395/24587562/3764701c-17b9-11e7-8b0d-d01e68ffa1cf.png)

**Comment by ryantxu** [comment]
this is now in master and will be release in version v0.0.3
