### ISSUE TITLE
Make newest realease (0.0.9) available through grafana plugin registry

### ISSUE THREAD

**Issue by clink-aaron** [NatelEnergy/grafana-discrete-panel#80]
Newest version available on the Grafana plugin registry is 0.0.8 (https://grafana.com/plugins/natel-discrete-panel).

**Comment by ryantxu** [comment]
it is kinda out of my hands... needs to get approved by grafana team and merged.  see:

https://github.com/grafana/grafana-plugin-repository/pull/351
