### ISSUE TITLE
Panel does not respect dashboard timezone setting on "default"

### ISSUE THREAD

**Issue by cartw** [NatelEnergy/grafana-discrete-panel#94]
We have set the default timezone in our grafana (currently 6.3.4) to be UTC so that all new dashboards will show consistent time. 

I noticed that the discrete panel does not respect the timezone when the dashboard is set to default but shows current browser time instead. For example the same metric plotted on a graph and discrete panel:
![image](https://user-images.githubusercontent.com/41674477/66374424-e061f280-e9a2-11e9-8b73-21af0bd963d8.png)

Note the discrete panel is an hour ahead. 

The relevant dashboard settings are 
![image](https://user-images.githubusercontent.com/41674477/66374461-f7084980-e9a2-11e9-8b8a-2f0d0b94e23c.png)
no timeshift is applied to either panel. 

If I explicitly set the dashboard to UTC it's fine so it seems it's only a problem when using the default setting.

**Comment by dmned-ph** [comment]
+1
